zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    bank-branch-service-eureka-client-n-config-server: /branches/**
    bank-customers-service-eureka-client-n-config-server: /customers/**
      

# To disable eureka client
eureka:
  client:
    eureka-server-port: 8761
    register-with-eureka: true
    fetch-registry: true
